# name: Deploy to AWS S3

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ AKIAVHNJY4FGSBDRH3GP }}
#           aws-secret-access-key: ${{ 5XT1KDLP/4PGoZ2/ThyGVk213o7+eeOdOFdrWMw5}}
#           aws-region: us-east-1   # Replace with your AWS region (US East (N. Virginia))

#       - name: Deploy to S3
#         run: aws s3 sync . s3://bucket4websites --delete   # Replace "bucket4websites" with your actual S3 bucket name
